### ISSUE TITLE
[BUG] Empty file/directory for FileDialog

### ISSUE THREAD

**Issue by EyeOfPython** [MoAlyousef/fltk-rs#300] opened 2020-09-30 11:31 UTC
**Describe the bug**
Using `FileDialog` always results in the empty string as file/directory on MacOS 10.15.5.

**To Reproduce**
## `Cargo.toml`:
```toml
[package]
name = "my-project"
version = "0.1.0"
edition = "2018"

[dependencies]
fltk = "0.9.2"
```

## `main.rs`:
```rust
use fltk::dialog::{FileDialog, FileDialogType};

fn main() {
    let mut dialog = FileDialog::new(FileDialogType::BrowseFile);
    dialog.show();
    println!("filename: {:?}", dialog.filename().as_path().to_str().unwrap());
    println!("directory: {:?}", dialog.directory().as_path().to_str().unwrap());
    for file in dialog.filenames() {
        println!("files: {:?}", file.as_path().to_str().unwrap());
    }
}
```

Results in:
```
filename: ""
directory: ""
```

**Expected behavior**
`dialog.filename()` / `dialog.directory()` should contain the selected path.

**Desktop (please complete the following information):**
 - OS: macOS 10.15

**Comment by MoAlyousef** [comment] 2020-09-30 13:14
I was also able to reproduce this in C++:
```cpp
#include <FL/platform.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Native_File_Chooser.H>

int main(int argc, char ** argv) {
  fl_open_display();
  auto chooser = new Fl_Native_File_Chooser();
  chooser->show();
  auto file = chooser->filename();
  printf("filename: %s\n", file);
}
```
It seems macos 10.15 changed its api since this also gives me:
```
WARNING: <NSOpenPanel: 0x7fd13541bf80> running implicitly; please run panels using NSSavePanel rather than NSApplication.
```
Which seems to be similar to other issues online:
https://github.com/xamarin/xamarin-macios/issues/6474

I'll also open an issue in the FLTK repo.

**Comment by MoAlyousef** [comment] 2020-10-05 13:35
Hi
A fix was added to the FLTK repo which I have also pulled into this repo (currently on master).
Can you check if it also works for you by building against this git repo:
```toml
[dependencies]
fltk = { git = "https://github.com/moalyousef/fltk-rs" }
```
Thank you

**Comment by MoAlyousef** [comment] 2020-10-05 19:53
Hello
This is supposed to be fixed in 0.9.4. Note that for the native macOS file dialog to run in a modal mode the app should be built as a bundle.

**Comment by EyeOfPython** [comment] 2020-10-06 12:26
Hey thanks for that update.

I don’t know what happened, but when I now run my example above (still on MacOS 10.15.5), I don’t get any dialog at all, on both 0.9.2 and 0.94.

Occasionally I get a `2020-10-06 14:19:11.469 fltk-demo[31279:938145] WARNING: <NSOpenPanel: 0x7f80dfa070e0> running implicitly; please run panels using NSSavePanel rather than NSApplication.`

Maybe it’s related with that!

**Comment by MoAlyousef** [comment] 2020-10-06 19:39
Can you try running cargo clean and building against the master branch?
I used to get that warning but no longer do.

**Comment by EyeOfPython** [comment] 2020-10-06 21:25
Same thing:

```
fltk-demo tobiasruck$ cargo run
    Updating git repository `https://github.com/moalyousef/fltk-rs`
   Compiling fltk-sys v0.9.4 (https://github.com/moalyousef/fltk-rs#816f82ed)
   Compiling fltk-derive v0.9.4 (https://github.com/moalyousef/fltk-rs#816f82ed)
   Compiling fltk v0.9.4 (https://github.com/moalyousef/fltk-rs#816f82ed)
   Compiling fltk-demo v0.1.0 (/private/tmp/playground/fltk-demo)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 12s
     Running `target/debug/fltk-demo`
```

And then absolutely nothing.

I’m again using this code:

```rust
use fltk::dialog::{FileDialog, FileDialogType};

fn main() {
    let mut dialog = FileDialog::new(FileDialogType::BrowseFile);
    dialog.show();
    println!("filename: {:?}", dialog.filename().as_path().to_str().unwrap());
    println!("directory: {:?}", dialog.directory().as_path().to_str().unwrap());
    for file in dialog.filenames() {
        println!("files: {:?}", file.as_path().to_str().unwrap());
    }
}
```

**Comment by MoAlyousef** [comment] 2020-10-06 22:00
Hmm I’ll take a deeper look this weekend. 

Unfortunately the only thing I can suggest for now is to use nfd-rs, which is a crate intended to show native file dialogs in modal and non-modal modes.

**Comment by EyeOfPython** [comment] 2020-10-07 10:21
Yes, I switched to `native-dialog = "0.4.3"`, which works for my use-case.

Thanks for your help!

**Closed** 2020-11-02 12:15 UTC
